name: PHP Codeception Tests - develop

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub-contrib/actions/.github/workflows/module-tests-develop-test.yml@main
    with:
      module-id: reportcontent
